spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/scorpio?useSSL=false
  username: root
  password: root
  initialization-mode: never
  hikari.max-lifetime: 60000

spring.jpa.show-sql: true

logging:
  path: ${projectDir}/logs
  level:
    root: INFO
    com.onlymaker.scorpio: DEBUG

app:
  name: ${APP}
  version: ${VERSION}

amazon:
  list:
    - marketplace: marketplace
      marketplace-id: marketplaceId
      marketplace-url: marketplaceUrl
      seller-id: sellerId
      auth-token: authToken
      access-key: accessKey
      secret-key: secretKey

fetcher:
  html: "0 0 0 * * *"
  mws: "0 0 12 * * *"
  order:
    retrospect:
      days: 3
