version: ${VERSION}

spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/scorpio?useSSL=false
  username: root
  password: root
  initialization-mode: never

spring.jpa.show-sql: true

logging:
  path: ${projectDir}/logs
  level:
    root: INFO
    com.onlymaker.scorpio: DEBUG

server:
  port: 80
  tomcat:
    accesslog:
      directory: \${logging.path}/tomcat
      enabled: true

management:
  info.git.mode: full
  endpoints.web:
    base-path: /${APP}
    exposure.include: health,info,logfile,loggers,prometheus

  metrics.export.prometheus.step: 10m

app:
  name: ${APP}
  version: ${VERSION}

amazon:
  list:
    - store: store
      marketplace: marketplace
      marketplace-id: marketplaceId
      marketplace-url: marketplaceUrl
      seller-id: sellerId
      auth-token: authToken
      access-key: accessKey
      secret-key: secretKey

fetcher:
  cron: "0 0 0 * * *"
  order:
    retrospect:
      days: 3
