version: ${VERSION}

spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/scorpio?useSSL=false
  username: root
  password: root
  initialization-mode: never

spring.jpa.show-sql: true

logging:
  path: ${projectDir}/logs
  level:
    root: INFO
    com.onlymaker.scorpio: DEBUG

server:
  port: 80
  tomcat:
    accesslog:
      directory: \${logging.path}/tomcat
      enabled: true

spring.mvc.throw-exception-if-no-handler-found: true

management:
  info.git.mode: full
  endpoints.web.exposure.include: env,health,httptrace,info,logfile,loggers,sessions
  metrics.export.prometheus.step: 10m

mws.mode: central
