version: ${VERSION}

spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/scorpio?useSSL=false
  username: root
  password: root
  initialization-mode: never

spring.jpa.show-sql: true

logging:
  path: ${projectDir}/logs
  level:
    root: INFO
    com.onlymaker.scorpio: DEBUG

mws.mode: central
